local vim = vim
local Plug = vim.fn['plug#']

vim.call('plug#begin')

Plug('williamboman/mason.nvim')
Plug('williamboman/mason-lspconfig.nvim')
Plug('neovim/nvim-lspconfig')
Plug('nvim-treesitter/nvim-treesitter')
Plug('nvim-lua/plenary.nvim')
Plug('nvim-telescope/telescope.nvim')
Plug('nvim-lualine/lualine.nvim')
Plug('nvim-tree/nvim-web-devicons')
Plug('saghen/blink.cmp')
Plug('morhetz/gruvbox')
Plug('https://codeberg.org/ziglang/zig.vim')
Plug('lukas-reineke/indent-blankline.nvim')
Plug('goolord/alpha-nvim')
Plug('romgrk/barbar.nvim')
Plug('gelguy/wilder.nvim')
Plug('ray-x/lsp_signature.nvim')
Plug('windwp/nvim-autopairs')
Plug('iamcco/markdown-preview.nvim', { ['do'] = function()
  vim.fn['mkdp#util#install']()
end, ['for'] = {'markdown', 'vim-plug'} })

vim.call('plug#end')

require("lsp.lsp")
require("config.autocmds")
require("config.mappings")
require("config.options")
require("lsp.lua")
require("lsp.zls")
require("lsp.rust")
require("lsp.ts_ls")
require("plugins.gruvbox")
require("plugins.blink")
require("plugins.lualine")
require("plugins.ibl")
require("plugins.alpha")
require("plugins.wilder")
require("plugins.autopairs")

vim.lsp.enable('lua_ls')
vim.lsp.enable('zls')

vim.cmd("colorscheme gruvbox")
